config/routes.rb
Rails.application.routes.draw do
  get 'my_orders/new'

  resources :orders

  get 'search_books/new'

  get 'my_books/new'

  get 'my_books/create'

  get 'my_books/destroy'

  get 'admin/index'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  get 'store/index'

  resources :books
   
  resources :sessions
  
  get 'say/hello'

  get 'say/goodbye'
  
  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new 
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  
  get 'logout' => 'sessions#destroy'

  root 'admin#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  has_one :order
  
  
  validates :title, :condition, :price, :isbn, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  #attr_accessible :email, :password, :password_confirmation
  #attr_accessor :password
  has_many :books
  has_many :orders
  validates :email, presence: true, uniqueness: true, format: { with: /[a-z]+-?[a-z]+\.[1-9]\d*@osu\.edu/, 
    message: "should be from OSU" }
  has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    #@books = Book.find_by_id('1')
     @books = Book.where(isbn: params[:search])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # SHOW is used to implement ORDER
  # GET /books/1
  # GET /books/1.json
  def show
 	@user=current_user
        #create new order with book id and user id
	addNewOrder(@book.id, @user.id)
        #send an email to author
	OrderNotifier.send_email(User.find(@book.user_id)).deliver
  end
  

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    #@user = current_user
    #Request.addRequest(book_id: @book.id, buyer_id: @user.id)
    #Order.create(:book_id =>  12, :buyer_id =>  3)
    #OrderNotifier.send_email(User.find(@book.user_id)).deliver
    
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    
    @user = current_user
    @book.user_id = @user.id
    
    respond_to do |format|
      if @book.save
        format.html { redirect_to my_books_new_path, notice: 'Book was successfully created.' }
        format.json { render :my_books, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
    
 
   
    
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :condition, :price, :isbn)
    end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  end

  def goodbye
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @books = Book.order(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:new, :create, :index]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:email)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User #{@user.email} was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: "User #{@user.email} was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/my_books_helper.rb
module MyBooksHelper
end

app/helpers/my_orders_helper.rb
module MyOrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper

def addNewOrder(bk_id,by_id)
  Order.create(book_id: bk_id, buyer_id: by_id)
end 

end

app/helpers/request_books_helper.rb
module RequestBooksHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/search_books_helper.rb
module SearchBooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    session[:user_id] = user.id
    self.current_user = user
  end
  
  #setter method
  def current_user=(user)
    @current_user = user
  end
  
  #getter method
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    session[:user_id] = nil
    self.current_user = nil
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def deny_access
    redirect_to sign_in_path, :notice => "Please Login to access store."
  end
  
  
  
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<% if session[:user_id] == nil %>
  <p class="emptyStoreMessage">You can look at the catalog in 'All Books' tab, but you have to Login to sell or buy.</p>
  <h4><%= link_to 'Login', login_path %></h4>
<% else %>


<%= form_tag("/admin", method: "get") do %>
  <p>
    <%= text_field_tag :search, params[:search], placeholder: 'Enter ISBN here'%>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

	<h3>Welcome <span class="usernameDisplay"><%= User.find(session[:user_id]).email%></span>!</h3>
	<% if notice %>
	<p id="notice"><%= notice %></p> 
	<% end %>



<% if @books.size == 0 %>
  <p id="emptyStoreMessage">No Seach Results</p>
<% else %>

      <table>
	<thead>
	  <tr>
	    <th>Title</th>
	    <th>Condition</th>
	    <th>Price</th>
	    <th>ISBN</th>
	    <th colspan="3"></th>
	  </tr>
	</thead>
	

	<tbody>
	  <% @books.each do |book| %>
	    <tr>
	      <td><%= book.title %></td>
	      <td><%= book.condition %></td>
	      <td><%= book.price %></td>
	      <td><%= book.isbn %></td>
	      <td><%= link_to 'Order', book %></td>
	    </tr>
	  <% end %>
	</tbody>
	
      </table>

<% end %>



<h4><%= link_to 'Logout', logout_path %></h4>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <title>Buckeye Protocol Onlie Book Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body background-color="E6E6FA" class=`<%= controller.controller_name %>`>
  <div id="banner">
    <image src="/images/bp_logo.png" style="width:800px;height:123px">
    <!<%= @page_title || "Bookshelf"%>>
  </div>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" background-color:"E6E6FA" >
      <ul class="nav navbar-nav">
	<li><%= link_to 'Home', admin_path %></li>
        <li><%= link_to 'All Books', books_path %></li>
	<% if session[:user_id] == nil %>
		<!-- Don't display 'My Books' or 'My Orders' because user has not logged in -->
	<% else %>
		<li><%= link_to 'My Books', my_books_new_path %></li>
		<li><%= link_to 'My Orders', my_orders_new_path %></li>
	<% end %>
      </ul>
     
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

</nav>
  <div class="panel panel-default" style="width:60%;margin-right:20%; margin-left:20%;text-aligh:center">
  <div class="panel-heading">
    <h3 class="panel-title"><strong>Knowledge Could Be Cheaper!</strong></h3>
  </div>
  <div class="panel-body">
    
   <div id="main">
      <%= yield %>
    </div>
  </div>
</div>

<footer style="text-align:center">Designed and built by Buckeye Protocol<Br/>Copyright:Buckeye Protocol, OSU</footer>
</body>
</html>

app/views/order_notifier/send_email.html.erb
<h1>Hi <%=h @user.email %>,</h1>
<h2>Congratulations!</h2>


<p>
  <%= @greeting %>Your book on 'Buckeye Protocol Book Exchange' has been ordered!
</p>

app/views/order_notifier/send_email.text.erb
OrderNotifier#send_email

<%= @greeting %>, find me in app/views/order_notifier/send_email.text.erb