config/routes.rb
Rails.application.routes.draw do
  get 'my_orders/new'

  resources :orders

  get 'search_books/new'

  get 'my_books/new'

  get 'my_books/create'

  get 'my_books/destroy'

  get 'admin/index'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  get 'store/index'

  resources :books
   
  resources :sessions
  
  get 'say/hello'

  get 'say/goodbye'
  
  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new 
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  
  get 'logout' => 'sessions#destroy'

  root 'admin#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  #attr_accessible :email, :password, :password_confirmation
  #attr_accessor :password
  has_many :books
  has_many :orders
  validates :email, presence: true, uniqueness: true, format: { with: /[a-z]+-?[a-z]+\.[1-9]\d*@osu\.edu/, 
    message: "should be from OSU" }
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:new, :create, :index]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:email)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User #{@user.email} was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: "User #{@user.email} was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% if session[:user_id] == nil %>
  <h1 class="emptyStoreMessage">NICE TRY!</h1> 
  <h2>You're not authorized to view this database!</h2>
 <% elsif User.find(session[:user_id]).email != 'weldemicael.1@osu.edu' %>
        <h2 class="emptyStoreMessage">You are not admin!</h2>
  	<h4><%= link_to 'Admin Login', login_path %></h4>
<% else %>

        <h1>Users Database</h1>
	<% if notice %>
	<p id="notice"><%= notice %></p>
	<% end %>

	<table>
	  <thead>
	    <tr>
	      <th>Email</th>
	      <th colspan="3"></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @users.each do |user| %>
	      <tr>
		<td><%= user.email %></td>
		<td><%= link_to 'Show', user %></td>
		<td><%= link_to 'Edit', edit_user_path(user) %></td>
		<td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>

	<br>

	<%= link_to 'New User', new_user_path %>

<% end %>

app/views/users/new.html.erb
<!--<h1>Signup</h1>

<%= render 'form' %>

<%= link_to 'Back to Login', login_path %>-->

<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>