config/routes.rb
Rails.application.routes.draw do
  get 'my_orders/new'

  resources :orders

  get 'search_books/new'

  get 'my_books/new'

  get 'my_books/create'

  get 'my_books/destroy'

  get 'admin/index'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  get 'store/index'

  resources :books
   
  resources :sessions
  
  get 'say/hello'

  get 'say/goodbye'
  
  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new 
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  
  get 'logout' => 'sessions#destroy'

  root 'admin#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:book_id, :buyer_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper

def addNewOrder(bk_id,by_id)
  Order.create(book_id: bk_id, buyer_id: by_id)
end 

end

app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :book_id %>
    <%= f.input :buyer_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<% if session[:user_id] == nil %>
  <h1 class="emptyStoreMessage">NICE TRY!</h1> 
  <h2>You're not authorized to view this database!</h2>
 <% elsif User.find(session[:user_id]).email != 'weldemicael.1@osu.edu' %>
        <h2 class="emptyStoreMessage">You are not admin!</h2>
  	<h4><%= link_to 'Admin Login', login_path %></h4>
<% else %>

	<h1>Orders Database:</h1>

	<table>
	  <thead>
	    <tr>
	      <th>Book</th>
	      <th>Buyer</th>
	      <th colspan="3"></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @orders.each do |order| %>
	      <tr>
		<td><%= order.book_id %></td>
		<td><%= order.buyer_id %></td>
		<td><%= link_to 'Show', order %></td>
		<td><%= link_to 'Edit', edit_order_path(order) %></td>
		<td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>

	<br>

	<%= link_to 'New Order', new_order_path %>

<% end %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @order.book_id %>
</p>

<p>
  <strong>Buyer:</strong>
  <%= @order.buyer_id %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>