config/routes.rb
Rails.application.routes.draw do
  get 'my_orders/new'

  resources :orders

  get 'search_books/new'

  get 'my_books/new'

  get 'my_books/create'

  get 'my_books/destroy'

  get 'admin/index'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  get 'store/index'

  resources :books
   
  resources :sessions
  
  get 'say/hello'

  get 'say/goodbye'
  
  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new 
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  
  get 'logout' => 'sessions#destroy'

  root 'admin#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  has_one :order
  
  
  validates :title, :condition, :price, :isbn, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # SHOW is used to implement ORDER
  # GET /books/1
  # GET /books/1.json
  def show
 	@user=current_user
        #create new order with book id and user id
	addNewOrder(@book.id, @user.id)
        #send an email to author
	OrderNotifier.send_email(User.find(@book.user_id)).deliver
  end
  

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    #@user = current_user
    #Request.addRequest(book_id: @book.id, buyer_id: @user.id)
    #Order.create(:book_id =>  12, :buyer_id =>  3)
    #OrderNotifier.send_email(User.find(@book.user_id)).deliver
    
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    
    @user = current_user
    @book.user_id = @user.id
    
    respond_to do |format|
      if @book.save
        format.html { redirect_to my_books_new_path, notice: 'Book was successfully created.' }
        format.json { render :my_books, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
    
 
   
    
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :condition, :price, :isbn)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :condition %><br>
    <%= f.text_field :condition %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', my_books_new_path %>

app/views/books/index.html.erb
<h1>Book Catalog:</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Condition</th>
      <th>Price</th>
      <th>ISBN</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book. title %></td>
        <td><%= book.condition %></td>
        <td><%= book.price %></td>
        <td><%= book.isbn %></td>
        <% if session[:user_id] != nil %>
        	<td><%= link_to 'Order', book %></td>
	<% end %>
        <!--<td><%= link_to 'Edit', edit_book_path(book) %></td>-->
        <!--<td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if session[:user_id] == nil %>
	<h4 class="emptyStoreMessage">You have not Logged in! Click the link below to Login:</h4>
	<h4><%= link_to 'Login', login_path %></h4>
<% else %>
	<h4><%= link_to 'Logout', logout_path %></h4>
<% end %>
<!--<%= link_to 'New Book', new_book_path %>-->



<!--
<h1>Books Store</h1>
<% @books.each do |book| %>
<dic class="entry">
<h3><%= book.title %></h3>
<h4><%= book.condition %></h4>
  <div class="price_line">
    <span class="price"><%= number_to_currency(book.price) %></span>
  
  </div>
</div>
<% end %>-->

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', my_books_new_path %>

app/views/books/place_order.html.erb
<h2>Thanks for your order</h2>

app/views/books/show.html.erb
<h2>Thanks!</h2>
<h3>You ordered the following book. Email has been sent to the seller.</h3>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book. title %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @book.condition %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>ISBN:</strong>
  <%= @book.isbn %>
</p>

<%= link_to 'Back', books_path %>